# Generated by Django 5.0.4 on 2024-04-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_books_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default='N/A', max_length=50, null=True, verbose_name='Category'),
        ),
    ]
